# Generated by Django 3.0.6 on 2020-05-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grzyb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latin', models.CharField(max_length=100)),
                ('edible', models.CharField(max_length=15)),
                ('occurence', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'grzyb',
            },
        ),
    ]
